
// TASK: balanced_expr. (Same task as efsm.frs.)
//
// CANDIDATE: @@fsm with a BOUNDED, SATURATING depth counter (K = 3).
//
// This is the candidate the Machine Family RFC's `int(lo..hi)` would produce: a
// finite-domain counter, so the `when` guard observes only finite information, so
// the whole machine is a genuine DFA — CERTIFIED REGULAR, with decidable
// equivalence, O(1) memory, the lot.
//
// It is also WRONG, and that is the point of including it.
//
// `int(0..K)` does not exist yet, so the saturation is written by hand — the
// semantics are identical: at the bound, `depth + 1 == depth`.
//
// EXPECTED VERDICT: FAIL(language-changed) — RFC-0056.1 D5.
//
// Bounding the depth does not APPROXIMATE the scanner; it CHANGES THE LANGUAGE IT
// RECOGNIZES. Past depth K the counter cannot distinguish K from K+1, so the
// closers unwind one bracket early and the region ends short — `accepted == true`,
// no diagnostic, and the tail leaks into whatever is scanned next.
//
// It will be the FASTEST candidate here, and zero-copy, and certified. A battery
// that ranked on cost would recommend it. That is exactly why correctness gates
// and cost never does.
// Generated by framec — RFC-0042 @@fsm (Rust backend).

pub trait BalancedExprK3Input { fn fsm_get(&self, i: usize) -> char; fn fsm_len(&self) -> usize; }
impl BalancedExprK3Input for Vec<char> { fn fsm_get(&self, i: usize) -> char { self[i] } fn fsm_len(&self) -> usize { self.len() } }
impl BalancedExprK3Input for &[char] { fn fsm_get(&self, i: usize) -> char { self[i] } fn fsm_len(&self) -> usize { self.len() } }
impl BalancedExprK3Input for &[u8] { fn fsm_get(&self, i: usize) -> char { self[i] as char } fn fsm_len(&self) -> usize { self.len() } }
impl BalancedExprK3Input for Vec<u8> { fn fsm_get(&self, i: usize) -> char { self[i] as char } fn fsm_len(&self) -> usize { self.len() } }
pub struct BalancedExprK3Fn<F: Fn(usize) -> char>(pub F, pub usize);
impl<F: Fn(usize) -> char> BalancedExprK3Input for BalancedExprK3Fn<F> { fn fsm_get(&self, i: usize) -> char { (self.0)(i) } fn fsm_len(&self) -> usize { self.1 } }

pub struct BalancedExprK3<I: BalancedExprK3Input> {
    pub accepted: bool,
    pub reject_position: usize,
    pub cursor: usize,
    pub return_value: i64,
    pub text: I,
    pub depth: i64,
    matched: String,
    enter: usize,
}

impl BalancedExprK3<Vec<char>> {
    pub fn new(text: Vec<char>) -> Self {
        let mut _m = Self::over(text);
        _m.run();
        if _m.accepted { _m.reject_position = 0; }
        _m
    }
}

impl<I: BalancedExprK3Input> BalancedExprK3<I> {
    pub fn over(text: I) -> Self {
        Self {
            accepted: false,
            reject_position: 0,
            cursor: 0,
            return_value: 0,
            text: text,
            depth: 0,
            matched: String::new(),
            enter: 0,
        }
    }

    pub fn scan_at(&mut self, start: usize) -> bool {
        self.cursor = start;
        self.accepted = false;
        self.reject_position = 0;
        self.return_value = 0;
        self.matched = String::new();
        self.enter = 0;
        self.depth = 0;
        self.run();
        if self.accepted { self.reject_position = 0; }
        self.accepted
    }

    fn dfa_match(&self, states: &[(&[(u32, u32, usize)], bool)], start: usize) -> i64 {
        let mut st = start;
        let mut pos = self.cursor;
        let n = self.text.fsm_len();
        let mut last: i64 = if states[st].1 { pos as i64 } else { -1 };
        while pos < n {
            let v: i64 = self.text.fsm_get(pos) as i64;
            let mut nxt: Option<usize> = None;
            for &(lo, hi, tgt) in states[st].0 {
                if (lo as i64) <= v && v <= (hi as i64) { nxt = Some(tgt); break; }
            }
            match nxt {
                Some(t) => { st = t; pos += 1; if states[st].1 { last = pos as i64; } }
                None => break,
            }
        }
        last
    }


    fn run(&mut self) {
        let mut state: i64 = 0;
        while state >= 0 {
            let _enter = self.enter;
            self.enter = 0;
            state = match state {
                0 => self.state_0(_enter),
                1 => self.state_1(_enter),
                _ => return,
            };
        }
    }

    fn state_0(&mut self, _enter: usize) -> i64 {
        const DFA_0: &[(&[(u32, u32, usize)], bool)] = &[(&[(40, 40, 1), (91, 91, 1), (123, 123, 1)], false), (&[], true)];
        let _r = self.dfa_match(DFA_0, 0);
        if _r >= 0 {
            self.matched = (self.cursor..(_r as usize)).map(|__k| self.text.fsm_get(__k)).collect();
            self.cursor = _r as usize;
            self.accepted = true;
            if self.depth < 3 {
                self.depth = self.depth + 1;
            }
            return 0;
        }
        const DFA_1: &[(&[(u32, u32, usize)], bool)] = &[(&[(41, 41, 1), (93, 93, 1), (125, 125, 1)], false), (&[], true)];
        let _r = self.dfa_match(DFA_1, 0);
        if _r >= 0 {
            self.matched = (self.cursor..(_r as usize)).map(|__k| self.text.fsm_get(__k)).collect();
            self.cursor = _r as usize;
            self.accepted = true;
            if self.depth > 0 {
                self.depth = self.depth - 1;
            }
            if self.depth == 0 {
                return 1;
            }
            if true {
                return 0;
            }
            self.accepted = false;
            self.reject_position = self.cursor;
            return -1;
        }
        const DFA_2: &[(&[(u32, u32, usize)], bool)] = &[(&[(0, 39, 1), (42, 90, 1), (92, 92, 1), (94, 122, 1), (124, 124, 1), (126, 255, 1)], false), (&[(0, 39, 1), (42, 90, 1), (92, 92, 1), (94, 122, 1), (124, 124, 1), (126, 255, 1)], true)];
        let _r = self.dfa_match(DFA_2, 0);
        if _r >= 0 {
            self.matched = (self.cursor..(_r as usize)).map(|__k| self.text.fsm_get(__k)).collect();
            self.cursor = _r as usize;
            self.accepted = true;
            return 0;
        }
        self.accepted = false;
        self.reject_position = self.cursor;
        -1
    }

    fn state_1(&mut self, _enter: usize) -> i64 {
        if _enter == 0 {
            self.return_value = (self.cursor as i64);
        }
        -1
    }

}
