// Prolog scanner — dogfooded as an RFC-0042 @@fsm recognizer.
//
// Recognizes the file-header prolog that `prolog_scanner.rs` matches by hand:
//
//     BOM?  [ \t\r\n]*  @@target  [ \t]+  <lang to end-of-line>
//
// Stage 1 consumes an optional UTF-8 BOM and leading whitespace; its accepting
// embedding action records `line_start` = the offset of `@@target` (the start
// of the returned span). Stage 2 matches the literal `@@target` (the `@` is
// escaped `\@` — a bare `@` is the Mode C sigil), one-or-more spaces/tabs, then
// a non-empty language token running to the newline (or EOF). On a full match
// `cursor` is the newline/EOF offset = the end of the span.
//
// The literal-`@` escape and the reject-vs-accept boundary mirror the hand
// scanner exactly; the wrapper maps (accepted, line_start, cursor) to the same
// `RegionSpan` / error that `PrologScanner::scan` returns.
// Generated by framec — RFC-0042 @@fsm (Rust backend).

pub struct PrologScan {
    pub accepted: bool,
    pub reject_position: usize,
    pub cursor: usize,
    pub return_value: bool,
    pub src: Vec<char>,
    pub line_start: i64,
    matched: String,
    enter: usize,
}

impl PrologScan {
    pub fn new(src: Vec<char>) -> Self {
        let mut _m = Self {
            accepted: false,
            reject_position: 0,
            cursor: 0,
            return_value: false,
            src: src,
            line_start: 0,
            matched: String::new(),
            enter: 0,
        };
        _m.run();
        if _m.accepted {
            _m.reject_position = 0;
        }
        _m
    }

    fn dfa_match(&self, states: &[(&[(u32, u32, usize)], bool)], start: usize) -> i64 {
        let mut st = start;
        let mut pos = self.cursor;
        let n = self.src.len();
        let mut last: i64 = if states[st].1 { pos as i64 } else { -1 };
        while pos < n {
            let v: i64 = self.src[pos] as i64;
            let mut nxt: Option<usize> = None;
            for &(lo, hi, tgt) in states[st].0 {
                if (lo as i64) <= v && v <= (hi as i64) {
                    nxt = Some(tgt);
                    break;
                }
            }
            match nxt {
                Some(t) => {
                    st = t;
                    pos += 1;
                    if states[st].1 {
                        last = pos as i64;
                    }
                }
                None => break,
            }
        }
        last
    }

    fn run(&mut self) {
        let mut state: i64 = 0;
        while state >= 0 {
            let _enter = self.enter;
            self.enter = 0;
            state = match state {
                0 => self.state_0(_enter),
                _ => return,
            };
        }
    }

    fn state_0(&mut self, _enter: usize) -> i64 {
        if _enter <= 0 {
            let _r = self.match_stage_0();
            if _r < 0 {
                self.accepted = false;
                self.reject_position = self.cursor;
                return -1;
            }
            self.matched = self.src[self.cursor..(_r as usize)].iter().collect();
            self.cursor = _r as usize;
            self.accepted = true;
        }
        if _enter <= 1 {
            const DFA_1: &[(&[(u32, u32, usize)], bool)] = &[
                (&[(64, 64, 1)], false),
                (&[(64, 64, 2)], false),
                (&[(116, 116, 3)], false),
                (&[(97, 97, 4)], false),
                (&[(114, 114, 5)], false),
                (&[(103, 103, 6)], false),
                (&[(101, 101, 7)], false),
                (&[(116, 116, 8)], false),
                (&[(9, 9, 9), (32, 32, 9)], false),
                (&[(0, 9, 10), (11, 12, 10), (14, 255, 10)], false),
                (&[(0, 9, 10), (11, 255, 10)], true),
            ];
            let _r = self.dfa_match(DFA_1, 0);
            if _r < 0 {
                self.accepted = false;
                self.reject_position = self.cursor;
                return -1;
            }
            self.matched = self.src[self.cursor..(_r as usize)].iter().collect();
            self.cursor = _r as usize;
            self.accepted = true;
        }
        if _enter <= 2 {
            self.return_value = true;
        }
        -1
    }

    fn match_stage_0(&mut self) -> i64 {
        const DFA_0: &[(&[(u32, u32, usize)], bool)] = &[
            (&[(9, 10, 1), (13, 13, 1), (32, 32, 1), (239, 239, 2)], true),
            (&[(9, 10, 1), (13, 13, 1), (32, 32, 1)], true),
            (&[(187, 187, 3)], false),
            (&[(191, 191, 1)], false),
        ];
        let _entry = self.cursor;
        let mut st = 0;
        let mut pos = _entry;
        let n = self.src.len();
        let mut last: i64 = if DFA_0[st].1 { pos as i64 } else { -1 };
        self.cursor = pos;
        while pos < n {
            let v: i64 = self.src[pos] as i64;
            let mut nxt: Option<usize> = None;
            for &(lo, hi, tgt) in DFA_0[st].0 {
                if (lo as i64) <= v && v <= (hi as i64) {
                    nxt = Some(tgt);
                    break;
                }
            }
            let Some(t) = nxt else {
                break;
            };
            st = t;
            pos += 1;
            self.cursor = pos;
            let _now = DFA_0[st].1;
            if _now {
                self.line_start = (self.cursor as i64);
            }
            if _now {
                last = pos as i64;
            }
        }
        self.cursor = _entry;
        last
    }
}
