// String lexer — dogfooded as an RFC-0042 @@fsm recognizer.
//
// Recognizes the quoted-string grammar that `Lexer::lex_string` matches by
// hand: a double- or single-quoted run where `\<any>` is an escape:
//
//     "([^"\\]|\\.)*"   |   '([^'\\]|\\.)*'
//
// Open and close quote are the same fixed character per alternative — two
// ordered-choice branches, not a backreference (which would be non-regular).
// The recognizer reports accept + `cursor` (one past the closing quote); an
// unterminated string does not match (the hand scanner's UnterminatedString).
// Building the unescaped content (drop each backslash, keep the next byte) is
// transformation, so it stays in the wrapper.
//
// (The literal `"`/`'` here exercise framec#103 — the @@fsm body closer must
// treat the regex literals as opaque rather than counting their quotes.)
// Generated by framec — RFC-0042 @@fsm (Rust backend).

pub trait StringScanInput { fn fsm_get(&self, i: usize) -> char; fn fsm_len(&self) -> usize; }
impl StringScanInput for Vec<char> { fn fsm_get(&self, i: usize) -> char { self[i] } fn fsm_len(&self) -> usize { self.len() } }
impl StringScanInput for &[char] { fn fsm_get(&self, i: usize) -> char { self[i] } fn fsm_len(&self) -> usize { self.len() } }
impl StringScanInput for &[u8] { fn fsm_get(&self, i: usize) -> char { self[i] as char } fn fsm_len(&self) -> usize { self.len() } }
impl StringScanInput for Vec<u8> { fn fsm_get(&self, i: usize) -> char { self[i] as char } fn fsm_len(&self) -> usize { self.len() } }
pub struct StringScanFn<F: Fn(usize) -> char>(pub F, pub usize);
impl<F: Fn(usize) -> char> StringScanInput for StringScanFn<F> { fn fsm_get(&self, i: usize) -> char { (self.0)(i) } fn fsm_len(&self) -> usize { self.1 } }

pub struct StringScan<I: StringScanInput> {
    pub accepted: bool,
    pub reject_position: usize,
    pub cursor: usize,
    pub return_value: bool,
    pub src: I,
    matched: String,
    enter: usize,
}

impl<I: StringScanInput> StringScan<I> {
    pub fn new(src: I) -> Self {
        let mut _m = Self::over(src);
        _m.run();
        if _m.accepted { _m.reject_position = 0; }
        _m
    }

    pub fn over(src: I) -> Self {
        Self {
            accepted: false,
            reject_position: 0,
            cursor: 0,
            return_value: false,
            src: src,
            matched: String::new(),
            enter: 0,
        }
    }

    pub fn scan_at(&mut self, start: usize) -> bool {
        self.cursor = start;
        self.accepted = false;
        self.reject_position = 0;
        self.return_value = false;
        self.matched = String::new();
        self.enter = 0;
        self.run();
        if self.accepted { self.reject_position = 0; }
        self.accepted
    }

    fn dfa_match(&self, states: &[(&[(u32, u32, usize)], bool)], start: usize) -> i64 {
        let mut st = start;
        let mut pos = self.cursor;
        let n = self.src.fsm_len();
        let mut last: i64 = if states[st].1 { pos as i64 } else { -1 };
        while pos < n {
            let v: i64 = self.src.fsm_get(pos) as i64;
            let mut nxt: Option<usize> = None;
            for &(lo, hi, tgt) in states[st].0 {
                if (lo as i64) <= v && v <= (hi as i64) { nxt = Some(tgt); break; }
            }
            match nxt {
                Some(t) => { st = t; pos += 1; if states[st].1 { last = pos as i64; } }
                None => break,
            }
        }
        last
    }


    fn run(&mut self) {
        let mut state: i64 = 0;
        while state >= 0 {
            let _enter = self.enter;
            self.enter = 0;
            state = match state {
                0 => self.state_0(_enter),
                _ => return,
            };
        }
    }

    fn state_0(&mut self, _enter: usize) -> i64 {
        const DFA_0: &[(&[(u32, u32, usize)], bool)] = &[(&[(34, 34, 1)], false), (&[(0, 33, 1), (34, 34, 2), (35, 91, 1), (92, 92, 3), (93, 255, 1)], false), (&[], true), (&[(0, 9, 1), (11, 255, 1)], false)];
        let _r = self.dfa_match(DFA_0, 0);
        if _r >= 0 {
            self.matched = (self.cursor..(_r as usize)).map(|__k| self.src.fsm_get(__k)).collect();
            self.cursor = _r as usize;
            self.accepted = true;
            self.return_value = true;
            return -1;
        }
        const DFA_1: &[(&[(u32, u32, usize)], bool)] = &[(&[(39, 39, 1)], false), (&[(0, 38, 1), (39, 39, 2), (40, 91, 1), (92, 92, 3), (93, 255, 1)], false), (&[], true), (&[(0, 9, 1), (11, 255, 1)], false)];
        let _r = self.dfa_match(DFA_1, 0);
        if _r >= 0 {
            self.matched = (self.cursor..(_r as usize)).map(|__k| self.src.fsm_get(__k)).collect();
            self.cursor = _r as usize;
            self.accepted = true;
            self.return_value = true;
            return -1;
        }
        self.accepted = false;
        self.reject_position = self.cursor;
        -1
    }

}
