// Number lexer — dogfooded as an RFC-0042 @@fsm recognizer.
//
// Recognizes the integer/float literal grammar that `Lexer::lex_number`
// matches by hand:
//
//     -?[0-9]+(\.[0-9]+)?
//
// A leading `-` is part of the token only because the lexer dispatches here on
// `-` *followed by a digit* (a bare `-` is `->` or unary handled elsewhere), so
// `[0-9]+` always follows. The fractional part `(\.[0-9]+)?` matches only when a
// `.` is followed by at least one digit — `123.` stays an int and leaves the
// `.` for the next token, exactly like the hand scanner.
//
// The recognizer reports accept + `cursor` (= token end). int-vs-float
// classification and the `parse::<i64>()` / `parse::<f64>()` value conversion
// are transformation, not recognition, so they stay in the wrapper: float iff
// the matched slice contains `.`.
// Generated by framec — RFC-0042 @@fsm (Rust backend).

pub trait NumberScanInput { fn fsm_get(&self, i: usize) -> char; fn fsm_len(&self) -> usize; }
impl NumberScanInput for Vec<char> { fn fsm_get(&self, i: usize) -> char { self[i] } fn fsm_len(&self) -> usize { self.len() } }
impl NumberScanInput for &[char] { fn fsm_get(&self, i: usize) -> char { self[i] } fn fsm_len(&self) -> usize { self.len() } }
impl NumberScanInput for &[u8] { fn fsm_get(&self, i: usize) -> char { self[i] as char } fn fsm_len(&self) -> usize { self.len() } }
impl NumberScanInput for Vec<u8> { fn fsm_get(&self, i: usize) -> char { self[i] as char } fn fsm_len(&self) -> usize { self.len() } }
pub struct NumberScanFn<F: Fn(usize) -> char>(pub F, pub usize);
impl<F: Fn(usize) -> char> NumberScanInput for NumberScanFn<F> { fn fsm_get(&self, i: usize) -> char { (self.0)(i) } fn fsm_len(&self) -> usize { self.1 } }

pub struct NumberScan<I: NumberScanInput> {
    pub accepted: bool,
    pub reject_position: usize,
    pub cursor: usize,
    pub return_value: bool,
    pub src: I,
    matched: String,
    enter: usize,
}

impl<I: NumberScanInput> NumberScan<I> {
    pub fn new(src: I) -> Self {
        let mut _m = Self::over(src);
        _m.run();
        if _m.accepted { _m.reject_position = 0; }
        _m
    }

    pub fn over(src: I) -> Self {
        Self {
            accepted: false,
            reject_position: 0,
            cursor: 0,
            return_value: false,
            src: src,
            matched: String::new(),
            enter: 0,
        }
    }

    pub fn scan_at(&mut self, start: usize) -> bool {
        self.cursor = start;
        self.accepted = false;
        self.reject_position = 0;
        self.return_value = false;
        self.matched = String::new();
        self.enter = 0;
        self.run();
        if self.accepted { self.reject_position = 0; }
        self.accepted
    }

    fn dfa_match(&self, states: &[(&[(u32, u32, usize)], bool)], start: usize) -> i64 {
        let mut st = start;
        let mut pos = self.cursor;
        let n = self.src.fsm_len();
        let mut last: i64 = if states[st].1 { pos as i64 } else { -1 };
        while pos < n {
            let v: i64 = self.src.fsm_get(pos) as i64;
            let mut nxt: Option<usize> = None;
            for &(lo, hi, tgt) in states[st].0 {
                if (lo as i64) <= v && v <= (hi as i64) { nxt = Some(tgt); break; }
            }
            match nxt {
                Some(t) => { st = t; pos += 1; if states[st].1 { last = pos as i64; } }
                None => break,
            }
        }
        last
    }


    fn run(&mut self) {
        let mut state: i64 = 0;
        while state >= 0 {
            let _enter = self.enter;
            self.enter = 0;
            state = match state {
                0 => self.state_0(_enter),
                _ => return,
            };
        }
    }

    fn state_0(&mut self, _enter: usize) -> i64 {
        if _enter == 0 {
            const DFA_0: &[(&[(u32, u32, usize)], bool)] = &[(&[(45, 45, 1), (48, 57, 2)], false), (&[(48, 57, 2)], false), (&[(46, 46, 3), (48, 57, 2)], true), (&[(48, 57, 4)], false), (&[(48, 57, 4)], true)];
            let _r = self.dfa_match(DFA_0, 0);
            if _r < 0 {
                self.accepted = false;
                self.reject_position = self.cursor;
                return -1;
            }
            self.matched = (self.cursor..(_r as usize)).map(|__k| self.src.fsm_get(__k)).collect();
            self.cursor = _r as usize;
            self.accepted = true;
        }
        if _enter <= 1 {
            self.return_value = true;
        }
        -1
    }

}
