// Identifier scanner — dogfooded as an RFC-0042 @@fsm recognizer.
//
// Recognizes the identifier shape that `Lexer::scan_identifier` consumes,
// entered (per the structural dispatch) on an alphabetic or `_` lead — digits
// route to the number lexer:
//
//     [A-Za-z_][A-Za-z0-9_]*
//
// The recognizer reports accept + `cursor` (= identifier end). Keyword
// classification (interface/machine/return/true/false/…) is a finite lookup
// over the recognized word — transformation, not recognition — so it stays in
// the wrapper, mirroring `lex_identifier_or_keyword`. The `push$`/`pop$` and
// section-colon composites are 1-char-lookahead lexer logic *around* the
// identifier, not part of identifier recognition, and are out of scope here.
// Generated by framec — RFC-0042 @@fsm (Rust backend).

pub struct IdentScan {
    pub accepted: bool,
    pub reject_position: usize,
    pub cursor: usize,
    pub return_value: bool,
    pub src: Vec<char>,
    matched: String,
    enter: usize,
}

impl IdentScan {
    pub fn new(src: Vec<char>) -> Self {
        let mut _m = Self {
            accepted: false,
            reject_position: 0,
            cursor: 0,
            return_value: false,
            src: src,
            matched: String::new(),
            enter: 0,
        };
        _m.run();
        if _m.accepted {
            _m.reject_position = 0;
        }
        _m
    }

    fn dfa_match(&self, states: &[(&[(u32, u32, usize)], bool)], start: usize) -> i64 {
        let mut st = start;
        let mut pos = self.cursor;
        let n = self.src.len();
        let mut last: i64 = if states[st].1 { pos as i64 } else { -1 };
        while pos < n {
            let v: i64 = self.src[pos] as i64;
            let mut nxt: Option<usize> = None;
            for &(lo, hi, tgt) in states[st].0 {
                if (lo as i64) <= v && v <= (hi as i64) {
                    nxt = Some(tgt);
                    break;
                }
            }
            match nxt {
                Some(t) => {
                    st = t;
                    pos += 1;
                    if states[st].1 {
                        last = pos as i64;
                    }
                }
                None => break,
            }
        }
        last
    }

    fn run(&mut self) {
        let mut state: i64 = 0;
        while state >= 0 {
            let _enter = self.enter;
            self.enter = 0;
            state = match state {
                0 => self.state_0(_enter),
                _ => return,
            };
        }
    }

    fn state_0(&mut self, _enter: usize) -> i64 {
        if _enter <= 0 {
            const DFA_0: &[(&[(u32, u32, usize)], bool)] = &[
                (&[(65, 90, 1), (95, 95, 1), (97, 122, 1)], false),
                (&[(48, 57, 1), (65, 90, 1), (95, 95, 1), (97, 122, 1)], true),
            ];
            let _r = self.dfa_match(DFA_0, 0);
            if _r < 0 {
                self.accepted = false;
                self.reject_position = self.cursor;
                return -1;
            }
            self.matched = self.src[self.cursor..(_r as usize)].iter().collect();
            self.cursor = _r as usize;
            self.accepted = true;
        }
        if _enter <= 1 {
            self.return_value = true;
        }
        -1
    }
}
